### ISSUE TITLE
Issues with get client request contents etc.

### ISSUE THREAD

**Issue by markalayev91** [sstur/nodeftpd#36]
Hi, First off I want to say that you've done a great job writing a simple to start up FTP server. I have a neat idea that requires me to override FTP requests so this is awesome. I've enjoyed starting it off but there are a few things that I would love if you can explain to me. 

1. How to get the name of the file being requested by the client? The original CONN object that you pass back doesn't seem to have it in there?
2. The way that you have it set up to override the methods of the FS object before passing it back to the success function is a bit complicated. I've got it to work but it seems to be redundant due to this flow:
a. Client performs request
b. NodeJS intercepts and allows for custom code
c. Custom code pulls data from data base
d. Write data into stream

So we don't need to overwrite the ability to write the data stream, but instead have the ability to pass simply pass a different data set to be read. Does this make sense? I don't think this is a big deal but it could definitely make it easier for more novice developers to work with this. 

I'd appreciate answers and I hope that once I get my hands dirty, I will be able to contribute back.

Thanks!

**Comment by sstur** [comment]
Regarding (2), I agree the `fs` API is a bit complicated to have to implement if your FTP server is not actually backed by the file-system. (I've run into this implementing [rest-ftp-proxy](https://www.npmjs.com/package/rest-ftp-proxy) and [shopify-ftp](https://www.npmjs.com/package/shopify-ftp)) but it's core to how this project is designed. I think it would be a large effort to use a different API, and would certainly justify a fork (or maybe a rewrite).
