### ISSUE TITLE
Remove console logging

### ISSUE THREAD

**Issue by rogierschouten** [sstur/nodeftpd#42]
I keep getting these 'Client connection closed' messages in the console. This is annoying because I use ftpd for unittests and it mixes with the test output. Is there any way I can turn that off?

**Comment by sstur** [comment]
You're right, there should be a way to turn this off. Thanks for opening this issue. I'll try to make a solution.

**Comment by phillipgreenii** [comment]
@rogierschouten How are you able to run unittests?  I have not found a way to make ftpd close without ctrl+c.  Is it related to #43?

**Comment by phillipgreenii** [comment]
@sstur How important is the multiple levels of logging?  In other projects I have seen https://www.npmjs.com/package/debug which users opt into using an environment variable.  It only supports one level though.  If that is acceptable, I can put together a PR in short time.  I'm wondering if the multiple levels of notification would be better suited as events which falls in line with the request in #38.

**Comment by rogierschouten** [comment]
@phillipgreenii   I vaguely remember having to close a socket which is given to you somewhere inside the connection object that is passed with the callback functions.  I'll be able to check this at work next Monday, will get back to you.

**Comment by rogierschouten** [comment]
@phillipgreenii here's what you do:

1) Attach a handler to the "client:connected" event and store the connection event you get.

2) When you want to dispose, do this:

```javascript
if (client.dataSocket) {
      client.dataSocket.destroy();
}
if (client.socket) {
      client.socket.destroy();
}
if (client.pasv) {
      client.pasv.close();
}
```

**Comment by sstur** [comment]
@rogierschouten that seems like a good solution to #43 but I don't know if it solves the issue with console.log being too noisy without an option to silence it. @phillipgreenii, I'd accept a PR to either expose a "silence the logging" option or refactor it a bit to use environment variables / dedicated logging package.

**Comment by sstur** [comment]
After looking at npm/debug I like it, particularly the colors in console. I'd prefer logLevels instead of names but this is better than what we have so feel free to use it and just assign names to where we have levels now.

**Comment by sstur** [comment]
This should be fixed now with better verbosity control. Let me know if this is still an issue and I'll re-open. Thanks!
