### ISSUE TITLE
RETR sending 150 when file isn't found

### ISSUE THREAD

**Issue by phillipgreenii** [sstur/nodeftpd#55]
I'm struggling with a situation where my ftp client is trying to download a file using RETR and it sees the 150 mark response, but there is no file contents.  Upon digging into the code, it looks like in both `_RETR_usingCreateReadStream` and `_RETR_usingReadFile` a 150 is send and then the 550 is send.  I thought perhaps there was a bug in the client I was using, but to verify I tried to find the FTP spec.  The best I found was this: http://cr.yp.to/ftp/retr.html which says 

> The server may reject the RETR request without first responding with a mark. In this case the
> server does not touch the data connection. RFC 959 allows code 550 for file-does-not-exist,
> permission-denied, etc., and code 450 for out-of-memory, disk-failure, etc.

So, should the 150 not be sent? or is the client wrong for not checking for 550 after 150?

**Comment by phillipgreenii** [comment]
Found the RFC: https://tools.ietf.org/html/rfc959, but it doesn't spell it out as definitely as I would like.  

> Command-Reply Sequences
> 
>         In this section, the command-reply sequence is presented.  Each
>          command is listed with its possible replies; command groups are
>          listed together.  Preliminary replies are listed first (with
>          their succeeding replies indented and under them), then
>          positive and negative completion, and finally intermediary
>          replies with the remaining commands from the sequence
>          following.  This listing forms the basis for the state
>          diagrams, which will be presented separately.
>  
>          ... removed for brevity ...
>                RETR
>                  125, 150
>                      (110)
>                      226, 250
>                      425, 426, 451
>                  450, 550
>                  500, 501, 421, 530

This leads me to believe that either (125/150) or (450/550) or (500/501/421/530) should be returned after a `RETR`.  Am I wrong?  Is this a bug?

**Comment by sstur** [comment]
Thanks @phillipgreenii! I have had similar trouble understanding the spec in cases like this. I believe you are interpreting it correctly. Thanks for the PR!
