### ISSUE TITLE
publish the latest to npm

### ISSUE THREAD

**Issue by phillipgreenii** [sstur/nodeftpd#57]
there is a bunch of changes in master that aren't showing up in npm.  Most notably is the bug fixes.  Can we get a more up-to-date version in npm?

**Comment by phillipgreenii** [comment]
Just as a FYI, I just recently used https://docs.npmjs.com/cli/version and http://docs.travis-ci.com/user/deployment/npm/ to setup travis to deploy to npm whenever `npm version` is called.  Check out https://github.com/phillipgreenii/node-ftp-stream/blob/master/package.json and https://github.com/phillipgreenii/node-ftp-stream/blob/master/.travis.yml from https://github.com/phillipgreenii/node-ftp-stream

**Comment by sstur** [comment]
Thanks @phillipgreenii. The latest bits have been published to npm.

**Comment by LoicMahieu** [comment]
Hi @sstur 
Just your information, last version published in npm seems to be `0.2.15` but repository's package.json is `0.2.14`.
Also, if you use the `npm version` command, it create git tag for each version which is really useful.
