### ISSUE TITLE
Configurable list of allowed verbs

### ISSUE THREAD

**Issue by pye2k** [sstur/nodeftpd#62]
I think of FTP generally as a legacy compatibility layer. Most of the time I find that the full array of verbs aren't necessary. Would it be useful to have the ability to turn off certain verbs altogether? E.g. block DELE or RMD (say, for an upload-only server that expects to be a data-sink)?

**Comment by mk-pmb** [comment]
Useful yes, i think. A white-list approach ("allowed verbs") is less error-prone than blocking each of the undesired verby with a deny-all.

**Comment by pye2k** [comment]
I suppose a whitelist will also work, since the target of having a fixed set of commands will be suitable only for clients that connect and perform actions programmatically. In that case, the client should be operating within a known set of pre-defined commands anyway. Making the server match this list sounds sane. I will make a change and submit a pull request.

**Comment by sstur** [comment]
Thanks for the pull request. I added a couple inline comments in the commit. Mostly looks great!

**Comment by sstur** [comment]
This is now fixed. Closing the issue. Thanks!
