### ISSUE TITLE
Rely on `close` event and not on `finish` for WriteStream

### ISSUE THREAD

**Issue by oleksiyk** [sstur/nodeftpd#76]
https://github.com/sstur/nodeftpd/blob/master/lib/ftpd.js#L1397

I know that `close` event is not documented but the problem with `finish` event is that it is emitted *before* the stream has actually closed its descriptors and finished cleanup:

https://github.com/nodejs/node/blob/master/lib/fs.js#L1924

For custom filesystem that implements `fs` module functionality it means it has no chance to do final commits to whatever backend it uses before `file:store` event is emitted or even before Ftp client receives `226 Closing data connection`.

**Comment by sstur** [comment]
@oleksiyk I'm not sure I entirely understand. So the following things happen in order:

 * ftpd opens write stream (storeStream)
 * storeStream.write() is called however many times
 * storeStream.end() is called by ftpd when client is finished sending data
 * storeStream emits 'finish' (all data has been flushed to the underlying system)
 * storeStream emits 'close' (file descriptor is now closed)

From the Node docs:

 > [WriteStream] 'finish' event: When the end() method has been called, and all data has been flushed to the underlying system, this event is emitted.

Maybe I'm not understanding your use case, but if you're implementing a custom filesystem then you are in charge of emitting the 'finish' event so you can do whatever you like, right? You have time between when ftpd calls `.end()` and you chose to emit 'finish'. You control when `file:store` event is emitted after which Ftp client receives `226 Closing data connection`.

**Comment by sstur** [comment]
Also, if we change it to rely on the undocumented 'close' event, then people who are using this now with their own `fs` implementations may not be emitting that event and it would be a breaking change, no?

**Comment by oleksiyk** [comment]
> Maybe I'm not understanding your use case, but if you're implementing a custom filesystem then you are in charge of emitting the 'finish' event so you can do whatever you like, right? You have time between when ftpd calls .end() and you chose to emit 'finish'. You control when file:store event is emitted after which Ftp client receives 226 Closing data connection.

When you implement your own Writeable stream you must inherit Node Writeable class, which does all behind the scenes, including emitting the `finish` event. So its not my own code emits `finish` and so I can't catch the moment before its emitted. Have a look at this issues and the PR:

https://github.com/nodejs/node/issues/2994
https://github.com/nodejs/node/issues/4672
https://github.com/nodejs/node/pull/2314

As you can see [here](https://github.com/nodejs/node/blob/master/lib/fs.js#L1850) and then [here](https://github.com/nodejs/node/blob/master/lib/fs.js#L2022) the fs.createWriteStream actually returns a stream that listens to `finish` event of its parent class, closes file descriptor and then emits the undocumented event `close`. And only if you (as stream consumer) will listen to `close` and not to `finish` you can be sure that descriptor is closed. For custom `fs` implementors the logic in `.close()` can be much bigger and very important.

By the way, this was the way nodeftpd was working previously: https://github.com/sstur/nodeftpd/commit/02da02755d9f54c20c8f36cdf2e957ec1e52a346#diff-3ca34067155216ea4ab61155b6154f4c

We can write the code that listens on both events, and if the stream has already been closed on `close` then `finish` will do nothing. This will work reliably.

**Comment by sstur** [comment]
Ahhh! I totally didn't get that your "custom filesystem that implements fs module functionality" *inherits* from Node's `Writable` class. I've implemented a custom filesystem module before and simply conformed to the subset of fs API that nodeftpd uses. I assume other people might have done the same.

I'll take a closer look at the links you mentioned and try to wrap my head around this issue. Thanks!

**Comment by oleksiyk** [comment]
> We can write the code that listens on both events, and if the stream has already been closed on close then finish will do nothing. This will work reliably.

I didn't think before writing this... `close` is emitted after `finish` so this won't work.

**Comment by oleksiyk** [comment]
I think I'll simply catch events from parent `Writable` and re-emit them as needed: https://github.com/oleksiyk/riakfs/commit/e1b38cd193590a44c8473a1ef64137e65e3d8d0e

Thanks!

**Comment by sstur** [comment]
Good solution. Too bad we have to monkey patch things, but luckily JS is flexible enough to allow this in a pinch.

**Comment by pps83** [comment]
FYI, I had similar issues with plain vanilla streams: if I try to access file from within 'finish' event sometimes I get errors reading that file (in my case I had a gz stream and I was getting incomplete stream error).

**Comment by mk-pmb** [comment]
@pps83 I guess with "within 'finish' event", you mean "very soon after the 'finish' event"? (e.g. you schedule some file access operations from within the event handler.) In this case it sounds like a race condition with the file system cache, in which case the other event isn't reliable either, you just had better luck with it. You may want to fsync your file and only start reading from it when the sync succeeded.

**Comment by pps83** [comment]
That was also my guess that somehow it was related to cache, yet, it shouldn't really matter, as the OS is supposed to reuse the cache and make it transparent. There are two other more likely cases: 1) my code had issues or some kind of data races, 2) fs stream code has issues. I'm inclined to believe that (1) is the most likely case :)

**Comment by m4heshd** [comment]
@mk-pmb you just single-handedly saved months of my work that was gonna go down the drain. Thank you. Continuous file operations shouldn't be done without calling `fsync()` after each one.

**Comment by mk-pmb** [comment]
Glad I could help. :-)
