### ISSUE TITLE
Does not support korean character in LIST command.

### ISSUE THREAD

**Issue by yuntaek** [sstur/nodeftpd#97]
I uploaded file has Korean character(KR UTF-8)using filezila. Howerver, the filename is not printed properly. Also 'delete' and 'rename'  operations do not work.  
I checked file list using 'ls' command in the root folder on the linux server, the file has the right name. 
I suppose that this problem could be in LIST command part. 

I attached full log from ftpd .

> Passive data event: connect
> FTP command: STOR Google 행아웃.lnk (**filename is recognized correctly**)
> A data connection exists
> File opened/created: /Google 행아웃.lnk
> Told client ok to send file data
> Passive data event: end
> Passive data event: close
> FTP command: CWD /
> FTP command: PWD
> FTP command: TYPE A
> FTP command: PASV
> Telling client that they can connect now
> Passive data event: connect
> FTP command: LIST
> Directory has 14 files
> A data connection exists
> Sending file list
> Passive data event: end
> Passive data event: close
> FTP command: CWD /
> FTP command: PWD
> FTP command: TYPE A
> FTP command: PASV
> Telling client that they can connect now
> Passive data event: connect
> FTP command: LIST
> Directory has 14 files
> A data connection exists
> Sending file list
> Passive data event: end
> Passive data event: close
> FTP command: DELE Google ?Dnlnk (**filename is not recognized**)
> Error deleting file: /Google ?Dnlnk, Error: ENOENT, unlink '/stg/ftp_root/Google ?Dnlnk'

**Comment by yuntaek** [comment]
I've solved this problem change the source. 
lib/ftpd.js:74 
`return socket.write(data, 'asscii', callback); -> return socket.write(data, 'utf-8', callback);`
My ftpd version is 0.2.15.

**Comment by BenasPaulikas** [comment]
Might be same issue with https://github.com/sstur/nodeftpd/issues/92 I will check

**Comment by oleksiyk** [comment]
I don't know what 0.2.15 is, but its code is older than the code in master (which is 0.2.14). And I guess it simply doesn't contain the UTF8 support added in PR75. NPM should be updated with newer version.

**Comment by yuntaek** [comment]
I've upgrade NPM to the latest version 3.8.0.
`$ npm -version
3.8.0`
But still 0.2.15 version is installed. 
Below is the info of the ftpd.

> $ npm info ftpd                                      
> { name: 'ftpd',                        
>   description: 'Node FTP Server',      
>   'dist-tags': { latest: '0.2.15' },   
>   versions:                            
>    [ '0.2.1',                          
>      '0.2.3',                          
>      '0.2.4',                          
>      '0.2.5',                          
>      '0.2.6',                          
>      '0.2.8',                          
>      '0.2.9',                          
>      '0.2.10',                         
>      '0.2.11',                         
>      '0.2.12',                         
>      '0.2.13',                         
>      '0.2.14',                         
>      '0.2.15' ],                       
>   maintainers: [ 'sstur <sstur@me.com>' ],
>   time:                                   
>    { modified: '2016-01-14T13:35:45.130Z',
>      created: '2013-12-10T06:19:17.306Z',
>      '0.2.1': '2013-12-10T06:19:20.197Z',
>      '0.2.3': '2013-12-10T07:13:04.411Z',
>      '0.2.4': '2013-12-13T03:27:01.791Z',
>      '0.2.5': '2014-01-29T02:48:42.729Z',
>      '0.2.6': '2014-02-03T15:31:51.655Z',
>      '0.2.8': '2014-03-07T23:36:59.613Z',
>      '0.2.9': '2014-03-19T07:01:28.212Z',
>      '0.2.10': '2014-04-16T22:17:53.488Z',
>      '0.2.11': '2014-10-29T08:20:31.453Z',
>      '0.2.12': '2015-10-18T02:47:10.382Z',
>      '0.2.13': '2016-01-13T22:55:45.885Z',
>      '0.2.14': '2016-01-14T00:41:33.945Z',
>      '0.2.15': '2016-01-14T13:35:45.130Z' },
>   author: 'sstur',
>   repository:
>    { type: 'git',
>      url: 'git+ssh://git@github.com/sstur/nodeftpd.git' },
>   readmeFilename: 'README.md',
>   keywords: [ 'ftp', 'ftp-server', 'ftpd' ],
>   contributors:
>    [ 'Alex Drummond (https://github.com/addrummond)',
>      'Eric Fong (https://github.com/ericfong)',
>      'headconnect (https://github.com/headconnect)',
>      'Andrew Johnston (https://github.com/billywhizz)',
>      'José F. Romaniello (https://github.com/jfromaniello)',
>      'Simon Sturmer (https://github.com/sstur)',
>      'Alan Szlosek (https://github.com/alanszlosek)',
>      'asylumfunk (https://github.com/asylumfunk)' ],
>   bugs: { url: 'https://github.com/sstur/nodeftpd/issues' },
>   license: 'BSD-2-Clause',
>   users: { romanenko: true, renekochdk: true, dimps: true },
>   homepage: 'https://github.com/sstur/nodeftpd#readme',
>   version: '0.2.15',
>   main: './lib/ftpd.js',
>   engines: { node: '>=0.10.0' },
>   scripts: { test: 'istanbul test _mocha' },
>   dependencies: { dateformat: '1.0.7-1.2.3' },
>   devDependencies:
>    { async: '~0.1.15',
>      mocha: '~1.17.1',
>      should: '~3.1.2',
>      jsftp: 'git://github.com/sergi/jsftp.git#master',
>      istanbul: '~0.2.4' },
>   gitHead: 'c2a54b331c76deae611ddf28077c69a4e42b7374',
>   dist:
>    { shasum: '877ead07ce6b5bd8b4c6e9ea270510924bbd099d',
>      tarball: 'http://registry.npmjs.org/ftpd/-/ftpd-0.2.15.tgz' },
>   directories: {} }

**Comment by yuntaek** [comment]
After I installed ftpd@0.2.14, the utf-8 issue is cleared. 
@oleksiyk , checks the package in npm repository, please.

**Comment by oleksiyk** [comment]
@yuntaek I'm not the maintainer of the package. All I know is that 0.2.15 has older code than 0.2.14.

**Comment by BenasPaulikas** [comment]
https://media.giphy.com/media/1M9fmo1WAFVK0/giphy.gif
